language: python
python:
  - "3.6"
# command to install dependencies
install:
  - git clone https://github.com/dftfeDevelopers/dftfe dftfeDevelopers/dftfe
  - cd dftfeDevelopers/dftfe
  - git checkout clone-scrapper
  - pip install -r requirements.txt
# command to run tests
script:
  - python gh_traffic_python.py dsambit # or py.test for Python versions 3.5 and below
  
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git commit --message "updated stats file"
  - git remote add origin-upload https://${GH_CLONE_SCRAPPER_TOKEN}@github.com/dftfeDevelopers/dftfe> /dev/null 2>&1
  - git push origin-upload clone-scrapper 
  

