language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python gh_traffic_python.py dsambit # or py.test for Python versions 3.5 and below
  - git add .
  - git commit -a -m "add file"
  - git remote add origin-upload https://${GH_CLONE_SCRAPPER_TOKEN}@github.com/dftfeDevelopers/dftfe> /dev/null 2>&1
  - git push --quiet --set-upstream origin-upload clone-scrapper 
  

